### ISSUE TITLE
Plugin stopped working as of yesterday I believe

### ISSUE THREAD

**Issue by Sasco1st** [AyrA/ZippyShare#2]
Another Zippyshare update?

Thanks for the plugin btw, it really makes using the Synology download station breeze :)

**Comment by AyrA** [comment]
Could you post one or two example URLs? I will fix it today.

**Comment by Sasco1st** [comment]
Sure:
https://www106.zippyshare.com/v/Zujqo6Ss/file.html
https://www81.zippyshare.com/v/Q4OwiYxS/file.html

Thanks for looking into it.

**Comment by AyrA** [comment]
Should be fixed now in [v7.0](https://github.com/AyrA/ZippyShare/releases/tag/v7.0). I was able to extract the proper download URL and tried to write it in a way that should work for slight changes in the mathematical operators.

If they keep doing this I will eventually try to find an alternative solution that involves actually running the JS but I haven't yet found a good way to do so.

**Comment by AyrA** [comment]
Please test and report back if it works or not.

**Comment by Sasco1st** [comment]
I could download but the file was labled as "Private File" in the download station and the file itself was also called that with .file extension. I was able to open the rar/zip with winrar and extract without issue however!

EDIT: But not the test links, they worked and were named just fine, so not sure why certain links do that!

**Comment by strejdashek** [comment]
Can confirm it's working as expected. Marvellous work. Thanks.

https://www43.zippyshare.com/v/O0mBy1bL/file.html
https://www43.zippyshare.com/v/rK9lJTRL/file.html
https://www43.zippyshare.com/v/ICRfeGHs/file.html
https://www43.zippyshare.com/v/5H23tj5n/file.html
https://www43.zippyshare.com/v/tAV145q1/file.html
https://www43.zippyshare.com/v/rImYfUmo/file.html
https://www43.zippyshare.com/v/pEHpGeO0/file.html

**Comment by Sasco1st** [comment]
Might be a file flag set this is one that is doing that private file thing:
https://www118.zippyshare.com/v/dlp3gXwj/file.html

Cheers

**Comment by AyrA** [comment]
It looks like zippyshare hides the file name if the upload is marked as private. The field I extract the name from only contains the "private file" string.

I just published version 8 now. This attempts to grab the file name from the javascript code if the field contains the known invalid name. Not sure how reliable this is, so it's only done if the name can't be obtained be regular means.

**Comment by AyrA** [comment]
I want to add here that I don't have a synology NAS anymore, so these fixes are not fully tested. I test them on my local PHP installation only.

**Comment by Sasco1st** [comment]
Confirmed working with private files, thanks a ton for continuing to fix this, especially since you don't have a synology now!
